#开发环境配置文件

#1.配置数据源
spring:
 datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/li?characterEncoding=utf8&&serverTimezone=UTC
   username: root
   password: 123456

#2.配置mybatis的mapXml保存路径
#mybatis:
#mapper-locations:
 #classpath: myBatis/*Mapper.xml

#3.开启mybatis的日志
#针对某一部分开启日志级别为info,持久化日志到指定路径
logging:
  level:
    com:
      example:
        demo: info
  file:
     path: D:/ideaWork/myBatis-boot/

#开启myBatis的日志输出
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl