#开发环境配置文件

#配置web服务器的参数,访问端口是8081，访问的根路径是SpringBoot
server:
  port: 8081
  servlet:
    context-path: /SpringBoot


#1.配置数据源
spring:
 datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf8&&serverTimezone=UTC
   username: root
   password: 123456
   druid:    #配置数据库连接池
         initial-size: 5 #连接池初始化大小
         min-idle: 10 #最小空闲连接数
         max-active: 20 #最大连接数
 mvc:  #配置mvc
   view:
     suffix: .html  #返回资源的后缀
     static-locattions:
        classpath: /static  #声明资源的位置
     static-path-pattern: /**resource


#2.配置mybatis开启myBatis的日志输出
mybatis:
  configuration:
     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: myBatis/*Mapper.xml


#3.开启mybatis的日志
#针对某一部分开启日志级别为info,持久化日志到指定路径
logging:
  level:
    com:
      example:
        demo: info
  #p配置的是相对路径，项目路径下的logs目录下
  file:
     path: logs
#配置绝对路径，日志的名字默认是spring-{date}.log
#  file:
#    path:D/log

